# Generated by Django 4.2.1 on 2023-06-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='url',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
