# Generated by Django 4.2.1 on 2023-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_url_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
